# Generated by Django 4.0.4 on 2022-06-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
