# Generated by Django 4.0.4 on 2022-06-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_review_owner_alter_review_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
